# Global variables
variables:
  project_name: "Documentation - Homepage"
  project_name_clean: "homepage"
  yarn_cache_folder: $(Pipeline.Workspace)/.yarn/cache

trigger:
  batch: true
  branches:
    include:
    - master
  tags:
    include:
    - "*"

pr:
- master

jobs:
- job: 'Build'
  displayName: "Build the documentation website"
  pool:
    vmImage: "ubuntu-latest"
  
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.15.x'
    displayName: 'Install Node.js 10.15.x'

  - powershell: |
      Rename-Item -Path "robots_qa.txt" -NewName "robots.txt"
      Remove-Item -Path "robots_prod.txt"
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    displayName: 'Rename robots.txt file for QA'

  - task: AzureFileCopy@3
    displayName: 'Copy files to Azure Storage Blob: qaisogeohelp/$web/$(project_name_clean)'
    inputs:
      SourcePath: '$(System.DefaultWorkingDirectory)'
      azureSubscription: 'Isogeo - MPN(82885610-5841-4749-8d71-46f56b643ad2)'
      Destination: 'AzureBlob'
      storage: 'qaisogeohelp'
      ContainerName: '$web'
