version: 2

defaults:
  golang_container: &golang_container
    docker:
      - image: circleci/golang:1-stretch

  filters: &default_filters
    tags:
      only: '/v[0-9]+(\.[0-9]+)*/'

jobs:
  deploy-qa:
    <<: *golang_container
    steps:
      - checkout

      - run:
          name: Rename robots.txt
          command: mv robots_qa.txt robots.txt

      - run:
          name: Install rclone
          command: go get github.com/ncw/rclone

      - deploy:
          name: Upload to Azure Blob Storage
          command: |
                rclone sync index.html qa:\$web --delete-after
                rclone sync 404.html qa:\$web --delete-after
                rclone sync favicon.png qa:\$web --delete-after
                rclone sync robots.txt qa:\$web --delete-after
                rclone sync css/ qa:\$web/css --delete-after
                rclone sync img/ qa:\$web/img --delete-after

  deploy-prod:
    <<: *golang_container
    steps:
      - checkout

      - run:
          name: Rename robots.txt
          command: mv robots_prod.txt robots.txt

      - run:
          name: Install rclone
          command: go get github.com/ncw/rclone

      - deploy:
          name: Upload to Azure Blob Storage
          command: |
                rclone sync index.html prod:\$web --delete-after
                rclone sync 404.html prod:\$web --delete-after
                rclone sync favicon.png prod:\$web --delete-after
                rclone sync robots.txt prod:\$web --delete-after
                rclone sync sitemap.xml prod:\$web --delete-after
                rclone sync sitemapindex.xml prod:\$web --delete-after

workflows:
  version: 2

  push:
    jobs:
      - deploy-qa:
          filters: *default_filters

      - deploy-prod:
          filters:
            <<: *default_filters
            branches:
              ignore: /.*/
