version: 2

defaults:
  golang_container: &golang_container
    working_directory: *workspace_root
    docker:
      - image: circleci/golang:1-stretch

  filters: &default_filters
    tags:
      only: '/v[0-9]+(\.[0-9]+)*/'

jobs:
  deploy-qa:
    <<: *golang_container
    steps:
      - checkout

      - run:
          name: Install rclone
          command: go get github.com/ncw/rclone

      - deploy:
          name: Upload to Azure Blob Storage
          command: rclone sync index.html qa:\$web --delete-after

  deploy-prod:
    <<: *golang_container
    steps:
      - checkout

      - run:
          name: Install rclone
          command: go get github.com/ncw/rclone

      - deploy:
          name: Upload to Azure Blob Storage
          command: rclone sync index.html prod:\$web


workflows:
  version: 2

  push:
    jobs:
      - deploy-qa

      - deploy-prod:
          requires:
            - checkout
          filters:
            <<: *default_filters
            branches:
              ignore: /.*/
